import { createContext, useContext, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, Shield, UserRound } from 'lucide-react'

export type SentinelRole = 'personnel' | 'welfare' | 'commander'
type DemoUser = { name: string; email: string; password: string; role: SentinelRole }
type SessionUser = Pick<DemoUser, 'name' | 'email' | 'role'>
const USERS_KEY = 'sentinel-demo-users-v1'
const SESSION_KEY = 'sentinel-demo-session-v1'
const destinations: Record<SentinelRole, string> = { personnel: '/personnel/dashboard', welfare: '/welfare/dashboard', commander: '/commander/dashboard' }
function readUsers(): DemoUser[] { try { const value = JSON.parse(localStorage.getItem(USERS_KEY) ?? '[]'); return Array.isArray(value) ? value : [] } catch { return [] } }
function readSession(): SessionUser | null { try { const raw = sessionStorage.getItem(SESSION_KEY) ?? localStorage.getItem(SESSION_KEY); const value = raw ? JSON.parse(raw) : null; return value && ['personnel', 'welfare', 'commander'].includes(value.role) ? value : null } catch { return null } }
type AuthApi = { user: SessionUser | null; create: (user: DemoUser) => string | null; login: (email: string, password: string, remember: boolean) => string | null; enterDemo: (role: SentinelRole) => void; logout: () => void }
const AuthContext = createContext<AuthApi | null>(null)
export function SentinelAuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<SessionUser | null>(() => readSession())
  const value = useMemo<AuthApi>(() => ({ user,
    create: (next) => { const users = readUsers(); if (users.some((item) => item.email.toLowerCase() === next.email.toLowerCase())) return 'An account with this email already exists on this device.'; localStorage.setItem(USERS_KEY, JSON.stringify([...users, next])); return null },
    login: (email, password, remember) => { const found = readUsers().find((item) => item.email.toLowerCase() === email.trim().toLowerCase() && item.password === password); if (!found) return 'We couldn’t match that email and password. Check your details or use demo access.'; const next = { name: found.name, email: found.email, role: found.role }; sessionStorage.removeItem(SESSION_KEY); localStorage.removeItem(SESSION_KEY); (remember ? localStorage : sessionStorage).setItem(SESSION_KEY, JSON.stringify(next)); setUser(next); return null },
    enterDemo: (role) => { const next = { name: role === 'personnel' ? 'Alex Morgan' : role === 'welfare' ? 'Taylor Reed' : 'Jordan Lee', email: `demo.${role}@sentinel.local`, role }; sessionStorage.setItem(SESSION_KEY, JSON.stringify(next)); localStorage.removeItem(SESSION_KEY); setUser(next) },
    logout: () => { sessionStorage.removeItem(SESSION_KEY); localStorage.removeItem(SESSION_KEY); setUser(null) },
  }), [user])
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}
export function useSentinelAuth() { const value = useContext(AuthContext); if (!value) throw new Error('useSentinelAuth must be inside SentinelAuthProvider'); return value }
export function SentinelProtected({ role, children }: { role: SentinelRole; children: ReactNode }) { const { user } = useSentinelAuth(); const location = useLocation(); if (!user) return <Navigate to="/login" state={{ from: location.pathname }} replace />; if (user.role !== role) return <Navigate to={destinations[user.role]} replace />; return <>{children}</> }

function AuthFrame({ children, heading, intro }: { children: ReactNode; heading: string; intro: string }) { return <main className="sentinel-auth"><section className="auth-welcome"><Link className="sentinel-brand" to="/" aria-label="SENTINEL home"><span className="brand-shield"><Shield size={20}/></span><span><b>SENTINEL</b><small>WELFARE INTELLIGENCE</small></span></Link><div className="auth-welcome-copy"><span className="overline">PEOPLE WHO PROTECT, DESERVE TO BE PROTECTED.</span><h1>Support starts<br/><em>with trust.</em></h1><p>A thoughtful space for wellbeing, early support and human connection.</p></div><div className="auth-assurance"><Shield size={16}/> Welfare-led · Privacy-first · Demo environment</div></section><section className="auth-form-panel"><div className="auth-form-wrap"><div className="auth-mobile-brand"><Link className="sentinel-brand" to="/"><span className="brand-shield"><Shield size={18}/></span><span><b>SENTINEL</b><small>WELFARE INTELLIGENCE</small></span></Link></div><div className="auth-kicker"><span className="live-dot"/> DEMO MODE</div><h2>{heading}</h2><p className="auth-intro">{intro}</p>{children}<p className="auth-disclaimer">Prototype access only. This demo stores account details in this browser; don’t use real or sensitive information.</p></div><footer>© 2026 SENTINEL <span>·</span> People-first welfare intelligence</footer></section></main> }

export function SentinelLoginPage() { const { user, login, enterDemo } = useSentinelAuth(); const navigate = useNavigate(); const location = useLocation(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(false); const [show, setShow] = useState(false); const [error, setError] = useState(''); if (user) return <Navigate to={destinations[user.role]} replace/>; const submit = (event: FormEvent) => { event.preventDefault(); setError(''); if (!email.trim() || !password) { setError('Enter your email and password.'); return } const message = login(email, password, remember); if (message) setError(message); else { const state = location.state as { from?: string } | null; navigate(state?.from ?? destinations[readSession()?.role ?? 'personnel'], { replace: true }) } }; return <AuthFrame heading="Welcome back" intro="Sign in to your SENTINEL workspace."><form className="sentinel-auth-form" onSubmit={submit} noValidate><label>Email address<span className="auth-input"><Mail size={17}/><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="username" placeholder="you@example.com"/></span></label><label>Password<span className="auth-input"><LockKeyhole size={17}/><input type={show?'text':'password'} value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password" placeholder="Enter your password"/><button type="button" className="auth-eye" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label><div className="auth-options"><label className="remember-option"><input type="checkbox" checked={remember} onChange={(e)=>setRemember(e.target.checked)}/> Remember me</label><span>Forgot password?</span></div>{error&&<p role="alert" className="auth-error">{error}</p>}<button className="auth-submit" type="submit">Sign in <ArrowRight size={16}/></button></form><div className="auth-separator"><span/>Quick demo access<span/></div><div className="demo-access-grid">{(['personnel','welfare','commander'] as SentinelRole[]).map((role)=><button key={role} type="button" onClick={()=>{enterDemo(role);navigate(destinations[role],{replace:true})}}><b>{role==='welfare'?'Welfare Officer':role[0].toUpperCase()+role.slice(1)}</b><small>Enter demo workspace</small></button>)}</div><p className="auth-switch">New to the demo? <Link to="/signup">Create an account</Link></p></AuthFrame> }

export function SentinelSignupPage() { const { user, create } = useSentinelAuth(); const navigate = useNavigate(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [role,setRole]=useState<SentinelRole>('personnel'); const [show,setShow]=useState(false); const [error,setError]=useState(''); if(user)return <Navigate to={destinations[user.role]} replace/>; const submit=(event:FormEvent)=>{event.preventDefault();setError('');if(name.trim().length<2)return setError('Enter your full name.');if(!/^\S+@\S+\.\S+$/.test(email.trim()))return setError('Enter a valid email address.');if(password.length<8)return setError('Use at least 8 characters for your password.');if(password!==confirm)return setError('Passwords do not match.');const issue=create({name:name.trim(),email:email.trim(),password,role});if(issue)return setError(issue);navigate('/login',{state:{message:'Your demo account is ready. Sign in to continue.'}})}; return <AuthFrame heading="Create your account" intro="Set up a local demo workspace."><form className="sentinel-auth-form" onSubmit={submit} noValidate><label>Full name<span className="auth-input"><UserRound size={17}/><input value={name} onChange={(e)=>setName(e.target.value)} autoComplete="name" placeholder="Your name"/></span></label><label>Email address<span className="auth-input"><Mail size={17}/><input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com"/></span></label><label>Password<span className="auth-input"><LockKeyhole size={17}/><input type={show?'text':'password'} value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="new-password" placeholder="At least 8 characters"/><button type="button" className="auth-eye" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label><label>Confirm password<span className="auth-input"><LockKeyhole size={17}/><input type={show?'text':'password'} value={confirm} onChange={(e)=>setConfirm(e.target.value)} autoComplete="new-password" placeholder="Re-enter your password"/></span></label><label>Demo role<select className="auth-select" value={role} onChange={(e)=>setRole(e.target.value as SentinelRole)}><option value="personnel">Personnel</option><option value="welfare">Welfare Officer</option><option value="commander">Commander</option></select></label><p className="auth-role-note">Role selection is for demonstration only. It does not grant real access.</p>{error&&<p role="alert" className="auth-error">{error}</p>}<button className="auth-submit" type="submit">Create demo account <ArrowRight size={16}/></button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthFrame> }
